### ISSUE TITLE
No horizontal scrolling for long nonbreakable code

### ISSUE THREAD

**Issue by rofrol** [elm-lang/package.elm-lang.org#215] opened 2016-12-28 17:17 UTC
Go to http://package.elm-lang.org/packages/rluiten/elm-date-extra/8.1.2/Date-Extra-Config and see non-breakable text which goes under side menu.

- Google Chrome Version 55.0.2883.87 m
- Windows 11

![chrome_package elm-lange org](https://cloud.githubusercontent.com/assets/28787/21527191/a8a9f434-cd29-11e6-8fd3-6fea821a5799.png)

**Comment by infertux** [comment] 2017-01-01 14:28
Duplicate of #201 ;)

**Closed** 2017-01-01 21:37 UTC
