### ISSUE TITLE
Incorrect link to http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest/Date-Format

### ISSUE THREAD

**Issue by rofrol** [elm-lang/package.elm-lang.org#214] opened 2016-12-28 10:55 UTC
When I'm on page http://package.elm-lang.org/packages/rluiten/elm-date-extra/1.1.0/Date-Format and click link in page presented as:

> The latest version of this package is [8.1.2](http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest/Date-Format)

I will see:

`problem with parameter 'version': Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)`

Correct link should be http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest/Date-Extra-Format

**Comment by ryantriangles** [comment] 2017-01-07 14:25
This is a bug with a few areas of the documentation. The same happens on [Html.App](http://package.elm-lang.org/packages/elm-lang/html/1.1.0/Html-App) for 1.1.0.

When you look up documentation for an outdated package, the warning will always point you to the documentation for the latest version. But instead of just linking to the root documentation for the package, it points you to the latest version of the same module you're looking at. If that module has been removed from the package, you get this error. Date.Format was replaced by Date.Extra.Format and Html.App no longer exists, so both of those break.

This is a bit of a problem, as old documentation pages turn up as high Google results with regularity and are still linked to all over the place (the StackOverflow documentation for the Elm Architecture points to the Html.App module all over the place right now, I'm going to update it).

**Comment by BobWhitelock** [comment] 2017-01-15 00:51
Related to this issue, the same error message can occur from other broken links, such as from invalid links within a package documentation itself like in https://github.com/elm-community/elm-test/pull/106. It would probably make sense to 404 instead in this case.

**Comment by JoshTGreenwood** [comment] 2017-02-02 20:27
I just stumbled across this as well, here's a gif:

![docs breaking](https://cloud.githubusercontent.com/assets/1872899/22566986/0fe499bc-e95c-11e6-9e09-e10dbf185465.gif)

**Comment by martincerny** [comment] 2017-02-18 14:06
This seems to be a duplicate of #195 (I however do not have rights to mark it as such)

**Closed** 2017-02-19 00:26 UTC
