### ISSUE TITLE
Non-0.16 compatible packages are shown as 0.16 compatible packages

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#141] opened 2015-12-01 19:23 UTC
The packages http://package.elm-lang.org/packages/JOEANDAVERDE/flex-html/1.0.0/ and http://package.elm-lang.org/packages/joeandaverde/flex-html/1.0.0/ are shown on the package site as if they were compatbile with Elm 0.16. But they aren't, given that the underlying `elm-package.json` looks like this:
```json
{
    "version": "1.0.0",
    "summary": "Flexbox layout for elm-html",
    "repository": "https://github.com/TheSeamau5/flex-html.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [
      "Flex"
    ],
    "dependencies": {
        "elm-lang/core": "1.1.1 <= v < 2.0.0",
        "evancz/elm-html": "2.0.0 <= v < 3.0.0"
    }
}
```

**Comment by evancz** [comment] 2015-12-02 20:56
I can fix this particular case. Do you have any ideas of how this happened? Was this published recently?

**Comment by evancz** [comment] 2015-12-02 20:58
Okay, they are removed from that list. @joeandaverde, what version of Elm are you working with?

**Comment by jvoigtlaender** [comment] 2015-12-02 21:41
It happened in https://github.com/elm-lang/elm-package/issues/180, apparently with some old version of Elm. See my comment from yesterday over there.

**Comment by joeandaverde** [comment] 2015-12-02 21:45
I am using Elm 0.16. 

Here's the situation:

I wanted to use flex-html published by another author. That author hadn't updated the module for 0.16.

I decided to clone the repository: 

https://github.com/TheSeamau5/flex-html/blob/afeea3e21dfe4ad65d9cd111be066ea58b9476b6/elm-package.json

I updated the `elm-package.json` to this: 

https://github.com/joeandaverde/flex-html/blob/5ef3b22b49e524dbdb2e7739ea2c46aecd76b7ad/elm-package.json


On my first attempt to publish the package I tried to use version `2.0.2` -- I didn't know that I couldn't publish a new package without it being version `1.0.0`. I modified the version as requested. 

I wasn't paying attention and updated the repository link to use my Github name but typed it in all caps. 

(these booboos were amended in git so aren't reflected in the `elm-package.json` above)

I realized my mistake in using all caps after visiting the package website and seeing the package name. I thought this wasn't pleasing so I looked to find a way to remove the package. I didn't see any way to do so. I figured why not try publishing it again with a lowercase name and see if it will update. This caused two packages to be created.

Hope this helps!

**Comment by joeandaverde** [comment] 2015-12-02 21:49
Oh, it's also worth mentioning that "elm-version" WAS in the elm-package.json file. 

I used elm package version 0.16.0

**Comment by joeandaverde** [comment] 2015-12-02 21:52
Here's my command line history: A bit embarrassing but may help.

       9823  git clone https://github.com/TheSeamau5/flex-html.git
       9824  cd flex-html
       9825  ls
       9826  elm-reactor
       9827  elm package install
       9828  ls
       9829  elm package update
       9830  elm package
       9831  elm-package diff
       9832  elm-package diff evancz/elm-html 1.2.1 2.0.0
       9833  atom .
       9834  elm-package diff coreytrampe/elm-vendor
       9835  elm-package install
       9836  elm-reactor
       9837  elm-package install
       9838  elm-reator
       9839  elm-reactor
       9840  elm
       9841  elm package
       9842  elm package bump
       9843  clear
       9844  ls
       9845  git status
       9846  git diff
       9847  git add .
       9848  git status
       9849  git commit -m "Update elm packages"
       9850  git remote rm origin
       9851  git remote add origin https://github.com/joeandaverde/flex-html
       9852  git push origin master
       9853  elm status
       9854  elm package
       9855  elm package publish
       9856  git  git tag -a 2.0.2 -m "release version 2.0.2"
       9857  git push origin 2.0.2
       9858  elm package publish
       9859  git add .
       9860  git status
       9861  git commit --amend
       9862  git push origin master
       9863  git push origin master -f
       9864  git push origin 2.0.2
       9865  git tag 2.0.2
       9866  git tag rm 2.0.2
       9867  git tag 2.0.2
       9868  git tag 2.0.2 -f
       9869  git push origin 2.0.2 -f
       9870  elm package publish
       9871  git status
       9872  git diff
       9873  git add .
       9874  git status
       9875  git commit --amend
       9876  git status
       9877  git push origin master -f
       9878  elm package publish

**Comment by jvoigtlaender** [comment] 2015-12-02 22:08
Now I'm seriously confused. I concluded that you were not using Elm 0.16 from the fact that your `elm-package.json` file didn't contain "elm-version" (and 0.16 wouldn't allow you to publish without that), AND from the fact that `elm-package` version 0.16 wouldn't let you publish an uppercase name.

The link http://package.elm-lang.org/packages/JOEANDAVERDE/flex-html/1.0.0/ you provided does contain an uppercase name, so I don't see how you can have managed to publish that with `elm-package` 0.16. Plus, despite you saying that there WAS an "elm-version" field, I see in https://github.com/joeandaverde/flex-html/blob/1.0.0/elm-package.json that there isn't.

**Comment by jvoigtlaender** [comment] 2015-12-02 22:12
How do you know that the `elm package` calls in the above command line history are calls to 0.16 version of `elm package`, not to some older version?

**Comment by joeandaverde** [comment] 2015-12-02 22:13
I don't know for sure besides I have elm 0.16 currently installed and I haven't installed anything differently for a while.

**Comment by jvoigtlaender** [comment] 2015-12-02 22:14
Well, you can probably check, in the same kind of environment as above, what `elm-package --version` is telling you?

**Comment by joeandaverde** [comment] 2015-12-02 22:14
I cloned the repo - it already had a 1.0.0 tag. Could that be a problem?

**Comment by joeandaverde** [comment] 2015-12-02 22:16
elm-package --version

      Invalid option `--version'

      elm package 0.16.0

**Comment by jvoigtlaender** [comment] 2015-12-02 22:17
I don't know whether a pre-existing tag would affect things here. My main confusion is still that by all I know it should be *impossible* to use `elm-package` 0.16 to publish a package with capitalized name and without "elm-version".

I'm also still confused about you saying that there is/was an "elm-version" versus me seeing in your repository that there isn't such a field. Can you clear this up?

**Comment by joeandaverde** [comment] 2015-12-02 22:19
The commit you linked above was from February. This was probably the original authors commit. In my command line output notice that I don't create a 1.0.0 tag. Does that help?

**Comment by joeandaverde** [comment] 2015-12-02 22:20
https://github.com/joeandaverde/flex-html/blob/2.0.2/elm-package.json

**Comment by jvoigtlaender** [comment] 2015-12-02 22:23
Well, no matter from when that commit I mentioned is. You did publish a version `1.0.0` of your library, didn't you? I see it at http://package.elm-lang.org/packages/joeandaverde/flex-html/1.0.0/. And the code uploaded for that version should have come from tag `1.0.0` of your repository. And in that tag version the `elm-package.json` doesn't have an "elm-version" field. In fact, I got to the link I gave above by clicking "Browse source" at http://package.elm-lang.org/packages/joeandaverde/flex-html/1.0.0/.

**Comment by jvoigtlaender** [comment] 2015-12-02 22:26
Maybe you have run into some bug where `elm-package` lets you publish a package under a wrong tag/version number? (In the sense that you say "I'm publishing 1.0.0", but actually you are in state where you have checked out `2.0.2` or whatever in your repository, and `elm-package` doesn't catch this mismatch but instead simply progresses and publishes inconsistent stuff.)

**Comment by joeandaverde** [comment] 2015-12-02 22:45
When the error message came up that I needed to publish 1.0.0 I did make the change to the json file. Does publishing the package pull from Github? If it did it pulled a tag that had already been in the repository committed by the original author.

**Comment by evancz** [comment] 2015-12-02 22:55
I haven't read this entire thread yet, but @jvoigtlaender, the lower case restriction is only for *project* names. People's user names can have capital letters in them.

**Comment by jvoigtlaender** [comment] 2015-12-02 22:59
Okay. @joeandaverde, your question can best be answered by @evancz as well.

But the overall problem here might be caused by any of https://github.com/elm-lang/elm-package/issues/110, https://github.com/elm-lang/elm-package/issues/106, https://github.com/elm-lang/elm-package/issues/138. And maybe there are other possible culprits over there as well.

**Comment by jvoigtlaender** [comment] 2015-12-03 05:30
@joeandaverde, did you notice that despite all your bumping and tagging and repeat publishing, which I assume you expected to publish versions `2.0.0` and `2.0.2` to the package site, http://package.elm-lang.org/packages/joeandaverde/flex-html still lists only exactly one version of the package, namely `1.0.0`?

**Comment by joeandaverde** [comment] 2015-12-03 06:23
I expected to publish `2.0.2` originally -- I now realize that it considered the package I was publishing as a brand new package. Therefore, it wanted me to publish `1.0.0`. I did so simply by updating the `elm-package.json` file and NOT updating the git tag.

Here's the original package versions: http://package.elm-lang.org/packages/TheSeamau5/flex-html

All of these versions were tagged in the original repo. 

After forking the repo (along with the tags) the package manager wanted me to publish `1.0.0`.

I did so by changing the version in the `elm-package.json` file. The package manager seemed to have detected the `1.0.0` tag and allowed me to publish. Even though the `1.0.0` tag did not represent the current set of code I was attempting to publish.

**Comment by jvoigtlaender** [comment] 2015-12-03 06:43
So it's one of the bugs/issues I already linked to yesterday, right?

**Comment by evancz** [comment] 2016-01-12 21:48
It seems like the title of this issue no longer captures what is going on here. @jvoigtlaender, can you close this issue and spawn off any remaining findings into more focused issues where the original comment explains everything? And please no "go read this thread to understand" links, because the problem is that I already do not know what's going on in this thread.

**Closed** 2016-01-13 06:32 UTC
