### ISSUE TITLE
Docs page > Package -- function annotation overflows container

### ISSUE THREAD

**Issue by newswim** [elm-lang/package.elm-lang.org#219] opened 2017-02-15 21:18 UTC
This may or may not be considered a bug, but it's kind of annoying to look at.

Navigate to: http://package.elm-lang.org/packages/elm-lang/core/latest/Platform

Appears in latest Firefox and Chrome.

<img width="1339" alt="screen shot 2017-02-15 at 3 09 08 pm" src="https://cloud.githubusercontent.com/assets/6667096/22995780/dc2eb630-f391-11e6-93b3-8e09870b81eb.png">

**Comment by zwilias** [comment] 2017-02-21 20:00
Dupe of #201

**Comment by evancz** [comment] 2017-07-11 01:05
I think the statement in #201 is nicer. I will add a link to this image from there though!

**Closed by evancz** 2017-07-11 01:05 UTC
