### ISSUE TITLE
Add build and contribution instructions

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/package.elm-lang.org#118] opened 2015-11-19 16:29 UTC
It would be nice for those of us who would like to contribute to this repo. At the moment, its not clear what the path is to build and run the package.elm-lang.

**Comment by jvoigtlaender** [comment] 2015-11-19 16:30
Duplicate of https://github.com/elm-lang/package.elm-lang.org/issues/110?

**Comment by Fresheyeball** [comment] 2015-11-19 16:31
@jvoigtlaender do you know how to build and serve this locally?

**Comment by jvoigtlaender** [comment] 2015-11-19 16:32
Yes. Done so for various feature implementations.

**Comment by Fresheyeball** [comment] 2015-11-19 16:33
@jvoigtlaender would you mind informing me?

**Comment by jvoigtlaender** [comment] 2015-11-19 16:34
Mainly it means following what I linked to above (via the referral to #110): https://github.com/elm-lang/elm-lang.org/blob/master/README.md

**Comment by Fresheyeball** [comment] 2015-11-19 16:36
Ok, cool. I will try that later.

**Comment by jvoigtlaender** [comment] 2015-11-19 16:43
I added "and contribution" to the title of the other issue and am closing this one here (to reduce indirections).

**Closed by jvoigtlaender** 2015-11-19 16:43 UTC

**Comment by Fresheyeball** [comment] 2015-11-19 18:54
Following those directions did not work for me:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-public-library-0.1 (user goal)
trying: snap-server-0.9.5.1 (dependency of elm-public-library-0.1)
trying: attoparsec-0.13.0.1 (dependency of snap-server-0.9.5.1)
trying: scientific-0.3.4.2 (dependency of attoparsec-0.13.0.1)
trying: vector-0.11.0.0 (dependency of scientific-0.3.4.2)
next goal: elm-package (dependency of elm-public-library-0.1)
rejecting: elm-package-0.5, 0.4, 0.2.2, 0.2.1, 0.2 (conflict:
vector==0.11.0.0, elm-package => vector>=0.10 && <0.11)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by jvoigtlaender** [comment] 2015-11-19 19:02
I'll need to see more context to try any diagnosis. Ideal would be the complete shell session with all commands and complete output.

**Comment by Fresheyeball** [comment] 2015-11-19 19:11
@jvoigtlaender 

```
Projects: git clone https://github.com/Fresheyeball/package.elm-lang.org.git
Cloning into 'package.elm-lang.org'...
remote: Counting objects: 1531, done.
remote: Compressing objects: 100% (249/249), done.
remote: Total 1531 (delta 123), reused 0 (delta 0), pack-reused 1281
Receiving objects: 100% (1531/1531), 336.08 KiB | 0 bytes/s, done.
Resolving deltas: 100% (967/967), done.
Checking connectivity... done.
Projects: cd package.elm-lang.org 
package.elm-lang.org(master): git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
package.elm-lang.org(master): cabal sandbox init --sandbox ../.cabal-sandbox
Writing a default package environment file to
/Users/isaac.shapira/Projects/package.elm-lang.org/cabal.sandbox.config
Creating a new sandbox at /Users/isaac.shapira/Projects/.cabal-sandbox
package.elm-lang.org(master): cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-public-library-0.1 (user goal)
trying: snap-server-0.9.5.1 (dependency of elm-public-library-0.1)
trying: attoparsec-0.13.0.1 (dependency of snap-server-0.9.5.1)
trying: scientific-0.3.4.2 (dependency of attoparsec-0.13.0.1)
trying: vector-0.11.0.0 (dependency of scientific-0.3.4.2)
next goal: elm-package (dependency of elm-public-library-0.1)
rejecting: elm-package-0.5, 0.4, 0.2.2, 0.2.1, 0.2 (conflict:
vector==0.11.0.0, elm-package => vector>=0.10 && <0.11)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by jvoigtlaender** [comment] 2015-11-19 19:25
Is that the whole session? Something should have happened before that in the parent directory (what `BuildFromSource.hs` does). The fact that there's
```
Creating a new sandbox at /Users/isaac.shapira/Projects/.cabal-sandbox
```
in the above means that something went wrong before. Because `BuildFromSource.hs` should have created a sandbox, which the `cabal install` here should be reusing, instead of creating a new one.

**Comment by Fresheyeball** [comment] 2015-11-19 19:30
I `rm`ed the entire directory and used a fresh terminal. That is the entire session.

**Comment by jvoigtlaender** [comment] 2015-11-19 19:32
Then you didn't follow the instructions at https://github.com/elm-lang/elm-lang.org/blob/master/README.md, right?

They say:
> First get the Elm developer workflow setup by reading the [build from source instructions][bfs-readme], then running [this script][bfs] with `runhaskell BuildFromSource.hs master`. Be aware that this is all the actively developed branches, so things may be in an intermediate state.

[bfs-readme]: https://github.com/elm-lang/elm-platform/blob/master/README.md
[bfs]: https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs

> Then in the `Elm-Platform/master/` directory, run these commands: ...

**Comment by Fresheyeball** [comment] 2015-11-19 20:07
Oop, you are right, I missed a bunch of stuff.

**Comment by jvoigtlaender** [comment] 2015-11-23 19:16
A rephrasing of the instructions is found in [this comment](https://github.com/elm-lang/package.elm-lang.org/issues/129#issuecomment-159029222).
